"""Rebuild the bundled Conquest layout from the pinned, BSD-licensed FreeDM WAD.

Adaptation: sample the union of sector footprints on a 64-Doom-unit grid,
flatten floors, open doors, discard disconnected pockets, and use box walls.
This imports the actual internet map layout, not Doom engine/game code.
"""
import hashlib
import json
import struct
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
wad = (ROOT / "assets/maps/freedm/dm01.wad").read_bytes()
count, directory = struct.unpack_from("<ii", wad, 4)
lumps = {}
for i in range(count):
    offset, size, name = struct.unpack_from("<ii8s", wad, directory + i * 16)
    lumps[name.rstrip(b"\0").decode()] = wad[offset:offset + size]
vertices = list(struct.iter_unpack("<hh", lumps["VERTEXES"]))
sides = [struct.unpack_from("<H", lumps["SIDEDEFS"], i + 28)[0]
         for i in range(0, len(lumps["SIDEDEFS"]), 30)]
edges = [[] for _ in range(len(lumps["SECTORS"]) // 26)]
for a, b, flags, special, tag, right, left in struct.iter_unpack("<7H", lumps["LINEDEFS"]):
    for side in [right, left]:
        if side != 65535:
            edges[sides[side]].append((vertices[a], vertices[b]))

def inside(x, y, polygon):
    crossings = 0
    for (ax, ay), (bx, by) in polygon:
        if (ay > y) != (by > y) and x < ax + (y - ay) * (bx - ax) / (by - ay):
            crossings += 1
    return crossings % 2 == 1

step = 64
min_x = min(x for x, y in vertices) // step * step - step
min_y = min(y for x, y in vertices) // step * step - step
width = (max(x for x, y in vertices) - min_x) // step + 2
height = (max(y for x, y in vertices) - min_y) // step + 2
walkable = {(x, y) for y in range(height) for x in range(width)
            if any(inside(min_x + (x + .5) * step, min_y + (y + .5) * step, p)
                   for p in edges)}
components = []
remaining = set(walkable)
while remaining:
    start = min(remaining)
    remaining.remove(start)
    component, queue = {start}, deque([start])
    while queue:
        x, y = queue.popleft()
        for p in [(x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)]:
            if p in remaining:
                remaining.remove(p)
                component.add(p)
                queue.append(p)
    components.append(component)
walkable = max(components, key=len)
data = {
    "name": "FreeDM Outpost",
    "source": "https://github.com/freedoom/freedoom/blob/v0.13.0/levels/dm01.wad",
    "license": "BSD-3-Clause",
    "sha256": hashlib.sha256(wad).hexdigest(),
    "cellSize": 1.6,
    "rows": ["".join("." if (x, y) in walkable else "#" for x in range(width))
             for y in range(height)],
}
target = ROOT / "src/maps/freedm-dm01.js"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text("// Generated by scripts/import-freedm.py. Original map: FreeDM v0.13.0, BSD-3-Clause.\n"
                  + "export const FREEDM_MAP = " + json.dumps(data, indent=2) + ";\n")
print(f"Imported {len(walkable)} walkable cells in a {width} x {height} map")
